config/routes.rb
Rails.application.routes.draw do
  resources :items

  get '/about' => 'static_pages#about'

  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  delete '/logout',
          to: 'sessions#destroy'

  resources :users,
            path_names: {new: "create account"}

  get '/password_reset' => 'users#password_reset'
  patch 'password_reset' => 'users#password_update'

  root 'static_pages#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :name, :description, :room, presence: true
  validates :purchase_price, numericality: true, allow_nil: true
  validates :room, format: {without: /Select One.../}
end

app/models/user.rb
class NameValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A[a-zA-Z]+\z/i
      record.errors[attribute] << (options[:message] || 'must contain only characters')
    end
  end
end

class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || 'is not an email')
    end
  end
end

class User < ActiveRecord::Base
  has_secure_password
  has_many :items
  validates :first_name, :last_name, name: true
  validates :email, email: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @user ||= User.find(session[:id]) if session[:id]
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.where(user_id: current_user).order('room')
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = current_user.items.build
  end

  def edit
  end

  def create
    @item = current_user.items.build(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was removed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :room, :purchase_price, :image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      #User provided valid password
      session[:id] = user.id
      redirect_to items_path,
        notice: "Welcome Back #{user.first_name.titleize}."
    else
      flash[:error] = 'Invalid email or password'
      render :login
    end
  end

  def destroy
    if user = current_user
      session[:id] = nil
      redirect_to root_path
        flash[:error] = "#{user.email} has been signed out."
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    if current_user
      redirect_to items_path
    end
  end

  def about
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :password_update]

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    session[:id] = @user.id
    redirect_to items_path,
      notice: "Thank you for signing up #{@user.first_name.titlecase}"
  else
    render :new
  end
end

def show
end

def edit
end

def update
  if @user.update(user_params)
    redirect_to edit_user_path(current_user), notice: 'Account Updated'
  else
    render :edit
  end
end

def password_reset
end

def password_update
  if @user.try(:authenticate, params[:current_password])
    if @user.update_attributes(user_params)
      redirect_to edit_user_path(current_user), notice: 'Your password has been updated'
    else
      flash[:alert] = 'Password not updated'
      render :edit
    end
  else
    flash[:alert] = 'Password not updated'
    render :edit
  end
end

private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/Users/_form.html.erb
<%= form_for(@user, html: { role: "form" }) do |f| %>
  <% if @user.errors.any? %>
    <div>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div>
      <%= f.text_field :first_name, class:'form_input', placeholder:'first name' %>
    </div>
  </div>
  <div>
    <div>
      <%= f.text_field :last_name, class:'form_input', placeholder:'last name' %>
    </div>
  </div>
  <div>
    <div>
      <%= f.text_field :email, class:'form_input', placeholder:'email' %>
    </div>
  </div>
  <div>
    <div>
      <%= f.password_field :password, class:'form_input', placeholder:'password' %>
    </div>
  </div>
  <div>
    <div>
      <%= f.password_field :password_confirmation, class:'form_input', placeholder:'confirm password' %>
    </div>
  </div>
  <div>
    <div>
      <%= f.submit 'Create Account', class: "button button_highlight", id:"create_account_button" %>
    </div>
  </div>
<% end %>

app/views/Users/new.html.erb
<div id="create_account_wrapper">

  <h1>Get Started Today</h1>

  <%= form_for(@user, html: { role: "form" }) do |f| %>
    <% if @user.errors.any? %>
      <div>
        <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <div>
        <%= f.text_field :first_name, class:'form_input', placeholder:'first name' %>
      </div>
    </div>
    <div>
      <div>
        <%= f.text_field :last_name, class:'form_input', placeholder:'last name' %>
      </div>
    </div>
    <div>
      <div>
        <%= f.text_field :email, class:'form_input', placeholder:'email' %>
      </div>
    </div>
    <div>
      <div>
        <%= f.password_field :password, class:'form_input', placeholder:'password' %>
      </div>
    </div>
    <div>
      <div>
        <%= f.password_field :password_confirmation, class:'form_input', placeholder:'confirm password' %>
      </div>
    </div>
    <div>
      <div>
        <%= f.submit 'Create Account', class: "button button_highlight", id:"create_account_button" %>
      </div>
    </div>
  <% end %>

</div>

app/views/items/_form.html.erb
<%= form_for @item, html: { multipart: true } do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div id="custom_room", class="field">
    <%= f.label :room %><br>
    <%= f.select( :room, options_for_select([['Select One...', 'Select One...'],['Family Room', 'Family Room'], ['Living Room', 'Living Room'], ['Kitchen', 'Kitchen'], ['Den', 'Den'], ['Master Bedroom', 'Master Bedroom'], ['Bedroom', 'Bedroom'], ['Office', 'Office']], f.object.room)) %>
  </div>
  <div class="field">
    <%= f.label :purchase_price %><br>
    <%= f.text_field :purchase_price, :precision => 2 %>
  </div>
  <% if @item.image_file_name? %>
    <%= image_tag @item.image.url(:medium) %>
  <% end %>
  <div class="field">
    <%= f.label 'Upload an image' %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Back', item_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Room</th>
      <th>Puchase price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= item.room %></td>
        <td><%= number_to_currency(item.purchase_price) %></td>
        <td><%= link_to 'Show', item %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Room:</strong>
  <%= @item.room %>
</p>

<p>
  <strong>Purchase price:</strong>
  <%= number_to_currency(@item.purchase_price) %>
</p>

<% unless @item.image_file_name? %>
  <p>You should upload a picture of this item!</p>
<% else %>
  <p><%= image_tag @item.image.url(:medium) %></p>
<% end %>

<%= link_to 'Edit', edit_item_path(@item) %>
<%= link_to 'Delete Item', item_path, method: :delete, data: { confirm: 'Are you sure you want to delete this item?' } %>
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecureInventory</title>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800,600' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="background <%= current_page?(root_path) || current_page?(new_user_path) || current_page?(about_path) || current_page?(login_path) ? "white" : "black" %>">
    <header>
      <div>
        <a class='logo' href= "/" <% root_path %> >secure<span id='logo_thin'>inventory</span></a>
      </div>
      <nav>
        <ul>
          <% if current_user %>
            <li class=" <%= 'active' if current_page?(items_path)%>"><%= link_to 'Your Inventory', items_path %></li>
            <li class=" <%= 'active' if current_page?(user_path(current_user))%>"><%= link_to 'Your Account', user_path(current_user) %></li>
            <li><%= link_to 'Sign Out', logout_path, method: :delete %></li>
          <% else %>
            <li class=" <%= 'active' if current_page?(about_path)%>" ><%= link_to 'About Us', about_path %></li>
            <li><%= link_to 'Create Account', new_user_path %></li>
            <li><%= link_to 'Sign In', login_path %>
          <% end %>
        </ul>
      </nav>
    </header>

    <%= yield %>

  </div>
</body>
</html>

app/views/static_pages/about.html.erb
<div id='text_block'>
  <p>In case of a homeowner’s insurance claim, you need to be able to provide proof of ownership of your belongings to make sure you get paid a fair amount.</p>
  <p>We provide a safe, secure way for you to store photos and details of your belongings in the cloud.</p>
  <p>That way, you never have to worry about your records being destroyed or lost.</p>
</div>


<div id='dark_background'>

    <div class="testimonial">
      <p class='blurb'>Mixtape bushwick migas, affogato chillwave +1 meggings mustache hammock vinyl umami occupy waistcoat. Artisan cornhole salvia offal</p>
      <%= image_tag 'profile_1.jpg', class:'picture' %>
    </div>
    <div class="testimonial">
      <p class='blurb'>Mixtape bushwick migas, affogato chillwave +1 meggings mustache hammock vinyl umami occupy waistcoat. Artisan cornhole salvia offal</p>
      <%= image_tag 'profile_2.jpg', class:'picture' %>
    </div>
    <div class="testimonial">
      <p class='blurb'>Mixtape bushwick migas, affogato chillwave +1 meggings mustache hammock vinyl umami occupy waistcoat. Artisan cornhole salvia offal</p>
      <%= image_tag 'profile_3.jpg', class:'picture' %>
    </div>

  <br>
  <div>
    <h2>get started today</h2>
    <%= link_to 'Create Account', new_user_path, class: 'button button_highlight' %>
  </div>
</div>

app/views/static_pages/index.html.erb
<h1 id="landing_title">create a secure record of your<br>belongings in case of the worst</h1>
<%= link_to 'Create Account', new_user_path, class: 'button button_highlight' %>
<%= link_to 'What We Do', about_path, class: 'button button_white' %>

app/views/users/edit.html.erb
<h2>Edit Your Information</h2>

<%= form_for(@user, html: { role: "form" }) do |f| %>
  <div>
    <div>
      <%= f.text_field :first_name, class:'form_input', placeholder:'first name' %>
    </div>
  </div>
  <div>
    <div>
      <%= f.text_field :last_name, class:'form_input', placeholder:'last name' %>
    </div>
  </div>
  <div>
    <div>
      <%= f.text_field :email, class:'form_input', placeholder:'email' %>
    </div>
  </div>
  <div>
    <div>
      <%= f.submit 'Save Changes', class: "button button_highlight", id:"edit_account_button" %>
    </div>
  </div>
<% end %>


<%= form_for(@user, url: password_reset_path, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@user.errors.count, "error") %> prohibited this profile from being saved:</h4>

      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div>
      <%= password_field_tag :current_password, params[:current_password], class:'form_input', placeholder: 'current password' %>
    </div>
  </div>

  <div>
    <div>
      <%= f.password_field :password, class:'form_input', placeholder: 'new password' %>
    </div>
  </div>
  <div>
    <div>
      <%= f.password_field :password_confirmation, class:'form_input', placeholder: 'confirm new password' %>
    </div>
  </div>

  <div>
    <div>
      <%= f.submit 'Update Password', class: 'button button_highlight' %>
    </div>
  </div>

  <%= link_to 'Back', users_path %>
<% end %>

app/views/users/show.html.erb
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
    </tr>
    <tr>
      <td><%= @user.first_name %></td>
      <td><%= @user.last_name %></td>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <td><%= link_to 'Edit Account', edit_user_path %></td>
    </tr>
  </thead>
</table>

app/views/welcome/index.html.erb
<div id="background">
  <header>
    <a><%= link_to 'secure', root_path, id: 'logo' %>
      <span><%= link_to "inventory", root_path, id: 'span-logo' %></span>
    </a>
    <nav>
      <ul>
        <li><%= link_to 'About Us', aboutus_path %></li>
        <li><%= link_to 'Create Account' %></li>
        <li><%= link_to 'Sign In' %>
      </ul>
    </nav>
  </header>
  <h1>when the worst happens<br>we're here for you</h1>
  <%= link_to 'Create Account', root_path, class: 'button button_highlight' %>
  <%= link_to 'About Us', aboutus_path, class: 'button button_white' %>
</div>